// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetMostFrequentWord provides a mock function with given fields: beginning
func (_m *Service) GetMostFrequentWord(beginning string) (string, error) {
	ret := _m.Called(beginning)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(beginning)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(beginning)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertWord provides a mock function with given fields: word
func (_m *Service) UpsertWord(word string) error {
	ret := _m.Called(word)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(word)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
